Homework 01
mrmegapolys/smart-home-2019 pull request #1
Opened 2019-10-12 16:31 UTC by mrmegapolys

Рожков Игорь

2019-10-12 16:32 UTC, mrmegapolys commented
Упростить сами ```eventProcesser```'ы можно, если изменить устройство самого дома. Как вариант, в комнатах можно иметь не ```Collection<Light>``` и ```Collection<Door>```, а ```HashMap<ObjectID, Device>```. Но поскольку это не защищает от дальнейшего изменения структуры дома (то, про что говорилось на занятии, например, объединение комнат в этажи) и сильно портит читаемость, решил оставить как есть.

2019-10-14 09:33 UTC, a-ivanov requested changes

2019-10-14 09:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        final String FILEPATH = "smart-home-1.js";
Зачем пременная final?

2019-10-14 09:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +            System.out.println("Smart home config not found.");
IOException может возникать не только при отсутствующем файле. Здесь можно выдавать более общее сообщение.

2019-10-14 09:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
> +    public static SmartHome fromJson(String encoded) {
Конечно зависит от контекста и использования, но здесь SRP скорее нарушен - класс и пишет, и читает SmartHome.
Исправьте.

2019-10-14 09:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventFactory.java
> +    public EventFactory() {
Конструктор автоматически создается компилятором, нет смысла объявлять его самому - лишний ненужный код.

2019-10-14 09:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventFactory.java
> +    public SensorEvent getNextSensorEvent(){
Создайте абстракцию через interface и имплементируйте ее. От этого будет большая польза в дальнейшем - можно будет легко менять имплементации (например, если мы захотим подключить внешнюю библиотеку от сентора).

2019-10-14 09:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/devices/ActionType.java
> +public interface ActionType {
В чем польза такого маркерного интерфейса? Давайте пока представим, что классы SensorEvent, SensorCommand, SensorEventType предоставляются со стороны "как есть" и необходимо пользоваться ими.

2019-10-14 09:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/devices/door/DoorEvent.java
> +public class DoorEvent extends SensorEvent {
См. комментарий к ActionType.

2019-10-14 09:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/devices/light/LightActionType.java
> +public enum LightActionType implements ActionType {
См. комментарий к ActionType.

2019-10-14 09:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/EventProcessors.java
> +public enum EventProcessors {
Вообще, enum лучше использовать для моделирования объектов, реализации которых по своей природе конечны (например, арифметические операции: -/*+, их больше нет и удобно представить в виде конечного enum).
А конфигурацию потенциально меняющихся зависимостей можно представить в отдельном "конфигурационном" классе.
Подумайте, куда у вас в коде это можно перенести и исправьте.

2019-10-14 09:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Dispatcher.java
> +        this.processors = createProcessors();
См. комментарий к EventProcessors.

2019-10-14 09:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/processors/DoorEventProcessor.java
> +                        if (room.getName().equals("hall")) {
Здесь нарушен SRP - обработка события с дверью и выполнения сценария "умного" дома.
Исправьте.

2019-10-15 10:48 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        final String FILEPATH = "smart-home-1.js";
Потому что это константа, почему бы ей не быть final?
Или Вы про то, что имя файла надо не хардкодить, а передавать аргументом командной строки?

@a-ivanov

2019-10-15 10:57 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +            System.out.println("Smart home config not found.");
Исправил

2019-10-15 11:00 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/EventFactory.java
> +    public EventFactory() {
Исправил

2019-10-15 11:10 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/EventFactory.java
> +    public SensorEvent getNextSensorEvent(){
Исправил

2019-10-15 12:41 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
> +    public static SmartHome fromJson(String encoded) {
Исправил

2019-10-15 13:28 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/devices/ActionType.java
> +public interface ActionType {
Польза в следующем:  поскольку разные устройства создают разные типы событий, удобно вместе с классом устройства хранить описание этих типов, у меня это enum-ы. Для гарантии того, что в поле события actionType лежит один из этих enum-ов, и сделана такая схема.

Я верю, что это решение может быть неидеально, но почему исходный SensorEventType, где собраны события от всех устройств, по причине чего он, кстати, не удовлетворяет SRP, лучше?
@a-ivanov

2019-10-15 14:00 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/EventProcessors.java
> +public enum EventProcessors {
Не очень понимаю, как должен выглядеть конфигурационный класс. Что-то написал, конечно, но не могу сказать, что мне самому нравится. 
Посмотрите, Вы это имели в виду?
@a-ivanov

2019-10-15 14:18 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/processors/DoorEventProcessor.java
> +                        if (room.getName().equals("hall")) {
Исправил

2019-10-16 19:43 UTC, iagoshkov requested changes
В целом хорошо, исправьте по комментариям.

2019-10-16 19:43 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SmartHome smartHome = SmartHomeSerializer.fromJson(encoded);
Сейчас SRP нарушен - много причин для изменения (формат сохранения дома, место его хранения - файл/сервис/БД).
Исправьте.

2019-10-16 19:43 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Dispatcher.java
> +    private final SmartHome smartHome;
Лучше вообще убрать отсюда ссылку на smartHome.
Если какому-то eventProcessor-у нужен smartHome - пусть он хранит ссылку на него у себя в поле.
Возможно, у нас будут processor-ы, которым smartHome не нужен или которым кроме smartHome нужны какие-то еще объекты - они должны инапсулировать знания о необходимых им для работы объекта внутри себя.
Поправьте.

2019-10-16 19:43 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/devices/SensorEvent.java
> +    public abstract String toString();
Зачем здесь объявлен метод toString() - он есть у любого объекта Java.

2019-10-16 19:43 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/devices/door/DoorEvent.java
> +    public String toString() {
Зачем наследоваться от SensorEvent - только ради override toString?
Можно реализацию toString объявить в родительском классе SensorEvent а не копипастить ее в каждом наследнике. У вас вывод этой команды практически одинаковый. По actionType итак понятно какой это event - Door или Light.

2019-10-16 19:43 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/devices/door/DoorEvent.java
> +    public String toString() {
Это просто добавляет лишней сложности.
Простой дизайн = меньше сущностей. Особенно когда особой необходимости в них нет.

2019-10-16 19:43 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/utils/Writer.java
> +    public static boolean writeStringToFile(String body, String filename) {
Такой метод лучше делать void и кидать Exception в случае неуспеха.
Именно для этого механизм Exception-ов и был придуман в Java, чтобы не возвращать разные коды ошибок и не заморачиваться с их обработкой и сделать чище код - чтобы основной flow программы читался шаг за шагом, а все exceptional cases были в catch блоках.

2019-10-17 13:56 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SmartHome smartHome = SmartHomeSerializer.fromJson(encoded);
Так это же main, где-то я ведь должен задавать конкретные параметры. Объекты, которые мне этот дом читают, SRP не нарушают, а тут я выбираю какие именно методы использовать.

@sbt-agoshkov

2019-10-17 14:06 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/Dispatcher.java
> +    private final SmartHome smartHome;
Исправил

2019-10-17 14:15 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/devices/door/DoorEvent.java
> +    public String toString() {
Я сделал это для того, чтобы явно печатать тип события. Сейчас по actionType понятно, а когда добавится, допустим, окно c actionType OPEN, CLOSED, то уже нельзя будет различить дверь и окно.

Но да, можно в SensorEvent переопределить toString и добавить туда имя класса через this.getClass().getSimpleName(). Исправлю.
@sbt-agoshkov

2019-10-17 14:16 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/devices/SensorEvent.java
> +    public abstract String toString();
См. ответ к комментарию ниже.

2019-10-17 14:34 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/devices/SensorEvent.java
> +    public abstract String toString();
Исправил

2019-10-17 14:34 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/devices/door/DoorEvent.java
> +    public String toString() {
Исправил

2019-10-17 14:41 UTC, a-ivanov requested changes
Что такое ProcessorFactory? Это абстракция для выполнения определенной responsibility? Тогда должен быть интерфейс. Подумайте, нужна ли такая абстракция вообще или нет.
Если это конфигурационный код, то почему он выделен в отдельный класс?
Подумайте и исправьте.

2019-10-17 14:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        final String FILEPATH = "smart-home-1.js";
Ну просто нет особого смысла делать локальну пременную final, тем более, если вам не нужно гарантий на ее переприсвоение (в методы передается значение указателя, поэтуому здесь final тоже не нужен).
В основном это нужно для полей класса - для хорошо спроектированного класса обычно поля не требуется переприсваивать, поэтому дополнительно их делают final.
Есл это константа - ее лучше вынести в поле класса, здесь это будет уместно.

2019-10-17 14:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SmartHome smartHome = SmartHomeSerializer.fromJson(encoded);
В классе Application находится "конфигурационный код" - в нем должны объявляться абстракции, инициализароваться имплементации с зависимостями и все.
В проекте должна присутствовать абстракция, которая позволит инциализировать SmartHome и конфигурационный код не будет знать деталей, как это было сделано. Передача имени файла - это ок, поскольку это аргументы для инициализации имплементации.

2019-10-17 14:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/devices/ActionType.java
> +public interface ActionType {
Исходный SensorEventType удовлетворяет SRP - он несет единственную функцию - задание всех возможных типов событий.
Можно ли разделить это на разные enum для разных объектов (дверь, свет)? В принципе можно, вопрос - зачем. Это усложняет код, а пользы никакой не приносит, потому, что в проекте есть одна абстракция - обработчик событий, реализация которой использует этим enum и ей достаточно одного enum.

2019-10-17 14:42 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/utils/Writer.java
> +    public static boolean writeStringToFile(String body, String filename) {
Исправил.
Кстати, как лучше делать: прокидывать exception наверх напрямую, как сейчас сделано, или, раз exception может появляться в разных местах, то ловить там, а наверх отдавать свой exception, возможно более информативный?

@sbt-agoshkov

2019-10-17 14:46 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/devices/SensorEvent.java
> +    public abstract String toString();
Исправил

2019-10-17 18:43 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        final String FILEPATH = "smart-home-1.js";
Ок, понял.

2019-10-17 19:00 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/devices/ActionType.java
> +public interface ActionType {
@a-ivanov 

Ну почему удовлетворяет? Менять его придется каждый раз, когда меняется хотя бы одно из устройств. Если же меняется что-то у двух устройств одновременно, то будут merge conflicts, поскольку люди из разных команд будут изменять один и тот же файл.

2019-10-17 19:53 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SmartHome smartHome = SmartHomeSerializer.fromJson(encoded);
Исправил

2019-10-19 08:38 UTC, iagoshkov approved these changes
Looks good

2019-10-19 08:41 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/utils/Writer.java
> +    public static boolean writeStringToFile(String body, String filename) {
На данном уровне абстракции (запись строки в файл) будет хорошо так, как вы сделали - кидать IOException.
Вообще, крайне рекомендую почитать EffectiveJava от Джошуа Блоха, там в т.ч. написано, как правильно пользоваться Exception-ами.

2019-10-21 22:27 UTC, a-ivanov approved these changes

2019-10-21 22:27 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/devices/ActionType.java
> +public interface ActionType {
Менять все равно что-то где-то придется) Дописать новый инстанс в enum - он для этого в том числе и существует, чтобы в него легко было добавлять новое. И merge конфликт в enum - одно из самых простых с точки зрения разрешения)
Здесь поступим так: если ты считаешь, что такое разделение принесет пользу в дальнейшем, пусть будет так. Через несколько заданий можешь вернуться к этому вопросу и оценить, насколько это решение стоило того.

2019-10-21 22:27 UTC, a-ivanov commented
Well done.

2019-10-21 22:30 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/scenarios/LightScenarios.java
> +public class LightScenarios {
Просто IMHO по стилю - то, что делает этот класс можно превратить в private метод в TurnLightsOffAfterLeaving.

2019-10-22 11:21 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/devices/ActionType.java
> +public interface ActionType {
Хорошо

2019-10-22 11:28 UTC, merged