Homework 05
mrmegapolys/smart-home-2019 pull request #6
Opened 2019-11-07 20:46 UTC by mrmegapolys

2019-11-14 22:45 UTC, a-ivanov requested changes
А где юнит-тесты для пульта и команд?

2019-11-14 22:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/CCEventProcessorAdapter.java
> +        switch (event.getEventType()) {
IMHO: вот если бы тут был сохранен исходный единый класс SensorEvent (параметризуемый enum EventType), то можно было бы добавить гибкую Map<String, EventType> (для адаптированного события нам нужен только EventType и objectId). В мапу легко добавлять новые типы событий из сторонней библиотеки в будущем.
А сейчас как здесь - хардкод и классическое противоречие OCP.

2019-11-14 22:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/MyConfiguration.java
> +        } catch (IOException e) {
Вот тут IOException можно вынести в сигнатуру метода smartHome (поскольку это конфигурационный код).

2019-11-14 22:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/MyConfiguration.java
> +        List<EventProcessor> processors = new ArrayList<>();
Можно каждого из обработчиков объявить отдельным бином:

```
@Bean
EventProcessor doorStateProcessor() {
    return new ActivatedAlarmDecorator(new DoorStateEventProcessor(smartHome()), alarm());
}

@Bean
...
```

А потом в бине для SensorEventsManager, где они все нужны, можно попрость Спринга собрать все бины из конфигурации типа EventProcessor автоматически:

```
@Bean
SensorEventsManager sensorEventsManager(Collection<EventProcessor> eventProcessors) {
...
}
```

Из плюсов - мы явно не харкодим обработчики в одном месте, объявляем по отдельности, легко выключаем при необходимости. Можно раскидать эти бины по разным конфигурациям.

2019-11-17 21:21 UTC, a-ivanov requested changes
По 4й дз:
- Уберите switch по типам событий в CCEventProcessorAdapter, там сейчас нарушение OCP. Подумайте, как можно использовать фабрики для создания событий (например, LightEvent) из строковых типов (например, "LightIsOff").
- В конфиге MyConfiguration уберите бин eventProcessors и переделайте через отдельные бины для каждого обработчика (как я описал в комментарии https://github.com/mrmegapolys/smart-home-2019/pull/6#discussion_r346576013).

По 5й дз:
- Создайте бины для RemoteControlRegistry, RemoteControlImpl и классов команд.
- Зарегистрируйте в RemoteControlImpl кнопки как в задании (лучше все сделать внутри конфигурации).
- Зарегистрируйте RemoteControlImpl в RemoteControlRegistry.
- Добавьте тесты по RemoteControlImpl и командам.

2019-11-17 22:13 UTC, a-ivanov requested changes

2019-11-17 22:13 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/remotecontrol/RemoteControlImpl.java
> +        if (!buttons.contains(buttonCode)) return;
ОДЗ значений кнопок гарантируется commands.keySet(), эта проверка лишняя.

2019-11-21 20:07 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/MyConfiguration.java
> +        } catch (IOException e) {
@a-ivanov а кто его ловить будет? или пусть падает?

2019-11-21 20:08 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/MyConfiguration.java
> +        List<EventProcessor> processors = new ArrayList<>();
Исправил

2019-11-23 11:53 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/MyConfiguration.java
> +        } catch (IOException e) {
@a-ivanov я сделал несколько по-другому, посмотрите. Мне кажется, это более информативно, чем просто IOException.

2019-11-25 10:50 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/MyConfiguration.java
> +        } catch (IOException e) {
Вижу. На практике если без готового состояния дома программа не может дальше работать, то достаточно упасть с IOException. Из текста должно быть понятно, что произошло и как починить.

2019-11-25 10:56 UTC, a-ivanov requested changes
Осталось объявить бины с объектами пульта, как я описал ранее, и заменить switch по типам событий в CCEventProcessorAdapter на фабрики или цепочку ответственности.

2019-11-25 10:56 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ProcessorsConfiguration.java
> +    private MainConfiguration main;
Этого делать не обязательно. Все бины из MainConfiguration спринг должен найти сам и подятнуть сюда. Необходимо объявить требуемые бины из MainConfiguration как аргументы в методах с созданием бинов здесь.

2019-11-25 10:56 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ProcessorsConfiguration.java
> +    EventProcessor doorStateEventProcessor() {
```
@Bean
    EventProcessor doorStateEventProcessor(SmartHome home) {
```

2019-11-26 19:21 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/ProcessorsConfiguration.java
> +    EventProcessor doorStateEventProcessor() {
@a-ivanov а если, допустим, в будущем мне надо будет в каком-то другом бине получать doorStateEventProcessor, то мне же тогда придется прокидывать smartHome туда.
В общем, если абстрагироваться от примера, вопрос такой, как лучше делать: зависимости добавлять в аргументы или держать их в локальных переменных?

2019-11-26 19:31 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/ProcessorsConfiguration.java
> +    EventProcessor doorStateEventProcessor() {
Вообще, по идее, чтобы не тащить везде smartHome как зависимость (а их может быть много разных), лучше в локальных переменных хранить, а не как аргумент передавать.

2019-11-26 19:35 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/ProcessorsConfiguration.java
> +    EventProcessor doorStateEventProcessor() {
@sbt-agoshkov @a-ivanov  кстати, еще такой вопрос, локальные переменные ж должны быть autowired, а идея на это ругается. Мы закрываем на это глаза потому что это конфигурация?

2019-11-29 10:24 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/CCEventProcessorAdapter.java
> +        switch (event.getEventType()) {
Да, в этом конкретном случае было бы лучше. А если бы в библиотеке были классы по устройствам, то было бы удобнее адаптировать мое решение. А если бы было что-то третье, оба решения проиграли бы. В реальном мире мы же не можем знать что придется адаптировать.

А вот до адаптера разделение событий по устройствам мне все же кажется более разумным решением. @a-ivanov

2019-11-29 10:31 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/CCEventProcessorAdapter.java
> +        switch (event.getEventType()) {
Но мой адаптер и правда не очень удачный получился, исправил:)
@a-ivanov

2019-11-29 10:34 UTC, mrmegapolys commented
Исправил замечания по 4 дз
@a-ivanov

2019-11-29 12:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ProcessorsConfiguration.java
> +    EventProcessor doorStateEventProcessor() {
> Вообще, по идее, чтобы не тащить везде smartHome как зависимость (а их может быть много разных), лучше в локальных переменных хранить, а не как аргумент передавать.

Для нашего случая, когда предполагается один дом на все, то по мне передавать аргументом - ок. Если бинов с домами будет несколько, то они все одного типа. И различать между ними можно либо через вызов конкретных методов в конфигурациях (аннотированные `@Bean`, как я понял вы оба имеете это под "локальными переменными"), либо через дополнительную аннотацию аргумента метода `@Qualified("beanName")`:

```
@Bean
SomeClass iNeedHome1(@Qualifier("home1") SmartHome home) {
...
}

@Bean
SomeClass iNeedHome2(@Qualifier("home2") SmartHome home) {
...
}
```

2019-11-29 20:14 UTC, a-ivanov requested changes
Не вижу исправлений в списке по 5й дз здесь https://github.com/mrmegapolys/smart-home-2019/pull/6#pullrequestreview-318045183

2019-11-29 20:14 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/adapters/ccsensorevent/CCEventProcessorAdapter.java
> +                return;
В Java можно не вызывать return.

2019-11-30 08:33 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/ProcessorsConfiguration.java
> +    EventProcessor doorStateEventProcessor() {
Я не совсем это имел в виду. Допустим, я сделал через аргументы: 
```@Bean
EventProcessor processor(SmartHome smartHome) { 
    return new Processor(smartHome)
}
```
Если в каком-то другом бине мне нужен будет этот класс, то мне придется добавлять smartHome и в его аргументы (ведь так?):
```@Bean
SomeInterface needProcessor(SmartHome smartHome) {
    return new NeedProcessor(processor(smartHome));
}
```
При этом needProcessor не имеет отношения к smartHome, соответственно, я не хочу, чтобы он был в сигнатуре. Как тогда быть?


Под локальными переменными я имел в виду такой подход:
```
@Autowired SmartHome smartHome;

@Bean
EventProcessor processor() {
    return new Processor(smartHome)
}

@Bean
SomeInterface needProcessor() {
    return new NeedProcessor(processor());
}
```

Отсутствие аргументов дает возможность создавать цепочки зависимостей любой длины и вообще вроде код выглядит чище.

2019-11-30 09:11 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/ProcessorsConfiguration.java
> +    private MainConfiguration main;
Обсуждение этого вопроса в следующем треде.

2019-11-30 11:55 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/smarthome/remotecontrol/RemoteControlImpl.java
> +        if (!buttons.contains(buttonCode)) return;
Исправил

2019-11-30 12:06 UTC, mrmegapolys commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/adapters/ccsensorevent/CCEventProcessorAdapter.java
> +                return;
Он здесь для того, чтобы после того, как нашелся нужный адаптер, не проходиться по остальным. Это, разумеется, в предположении о том, что одному внешнему событию соответствует не больше одного внутреннего. Но я не смог придумать адекватного сценария, где это нарушалось бы, поэтому считаю предположение разумным.

2019-12-02 08:30 UTC, a-ivanov approved these changes

2019-12-02 16:45 UTC, merged